"""add_mixed_media

Revision ID: 1c6e64b3ddd6
Revises: 85badb76fef7
Create Date: 2026-03-10 16:12:28.613191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6e64b3ddd6'
down_revision = '85badb76fef7'
branch_labels = None
depends_on = None

# use flask db upgrade to get the update
def upgrade():
    op.execute(
        "INSERT INTO tool (id, name) VALUES (4, 'Mixed Media')"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
