"""Add bio column to User

Revision ID: 85badb76fef7
Revises: a602a2876f5d
Create Date: 2025-04-24 16:45:12.420725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85badb76fef7'
down_revision = 'a602a2876f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
